name: Build C++ Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang make libboost-all-dev libsqlite3-dev cmake
          # Install ASIO (required by Crow)
          sudo apt-get install -y libasio-dev
          # Install Crow framework
          git clone https://github.com/CrowCpp/Crow.git
          cd Crow
          mkdir build && cd build
          cmake .. -DCROW_BUILD_EXAMPLES=OFF -DCROW_BUILD_TESTS=OFF
          make install

      - name: Build backend
        working-directory: backend
        run: make all

      - name: Upload built executable (optional)
        uses: actions/upload-artifact@v4
        with:
          name: api_server
          path: backend/api_server
